variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "shared_subnet" {}
variable "application_insights_id" {}
variable "key_vault_id" {}
variable "storage_account_id" {}
variable "container_registry_id" {}
variable "core_vnet" {}
variable "log_analytics_workspace_id" {}